package insane96mcp.explosionoverhaul.feature;

import insane96mcp.explosionoverhaul.ExplosionOverhaul;
import insane96mcp.explosionoverhaul.mixin.accessor.ExplosionAccessor;
import insane96mcp.insanelib.core.ModNBTData;
import insane96mcp.insanelib.core.feature.Feature;
import insane96mcp.insanelib.core.feature.LoadFeature;
import insane96mcp.insanelib.core.feature.Module;
import insane96mcp.insanelib.core.feature.config.Config;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.tags.TagKey;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.LivingEntity;
import net.minecraft.world.level.Explosion;
import net.minecraft.world.level.GameRules;
import net.minecraft.world.level.block.Block;
import net.neoforged.bus.api.EventPriority;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.neoforge.event.level.ExplosionEvent;

import javax.annotation.Nullable;

@LoadFeature(canBeDisabled = false)
public class BaseFeature extends Feature {
	public static ResourceLocation BASE_RESISTANCE_ADD_TAG;
	public static ResourceLocation RAY_STRENGTH_MULTIPLIER_TAG;
	public static ResourceLocation KNOCKBACK_MULTIPLIER_TAG;
	public static ResourceLocation DAMAGE_MULTIPLIER_TAG;

	public static final TagKey<EntityType<?>> KNOCKBACK_BLACKLIST = TagKey.create(Registries.ENTITY_TYPE, ExplosionOverhaul.location("explosion_knockback_blacklist"));
	public static final TagKey<EntityType<?>> ENTITY_BLACKLIST = TagKey.create(Registries.ENTITY_TYPE, ExplosionOverhaul.location("explosion_entity_blacklist"));
	public static final TagKey<Block> FLYING_BLOCKS_EXPLOSION_BLACKLIST = TagKey.create(Registries.BLOCK, ExplosionOverhaul.location("flying_blocks_explosion_blacklist"));
	public static final GameRules.Key<GameRules.BooleanValue> RULE_MOBGRIEFING = GameRules.register("explosionovehaul:griefing", GameRules.Category.MISC, GameRules.BooleanValue.create(true));

	@Config(description = "Vanilla Explosions use a random number that changes the explosion power. With this enabled the ray strength will be as the explosion size.")
	public static Boolean disableExplosionRandomness = true;
	//@Config(description = "Somewhere around 1.15 Mojang (for performance issues) removed the poof particles from Explosions. Keep them disabled if you have a low end PC.\nThese particles aren't shown when explosion power is <= 1")
	//public static Boolean enablePoofParticles = true;
	//@Config(description = "Removes the particles spawned by the explosion.")
	//public static Boolean disableEmitterParticles = true;
	@Config(description = "While enabled knockback is greatly increased by explosion size")
	public static Boolean knockbackScalesWithSize = true;
	@Config(description = "Explosions will generate from the middle of the entity instead of bottom of their bounding box.")
	public static Boolean explosionAtHalfEntity = true;
	@Config(description = "EXPERIMENTAL! This will make explosion blast blocks away. Blocks that can't land will drop the block as a TNT would have destroyed it.")
	public static Boolean enableFlyingBlocks = false;
	@Config(description = "If true, creepers explosions will drop no blocks.")
	public static Boolean creeperCollateral = false;
	@Config
	public static Double knockbackMultiplier = 1d;
	@Config(description = "Damage multiplier. Mobs can have a damage_multiplier nbt tag that will override this.")
	public static Double damageMultiplier = 0.85d;
	@Config(description = "Disabled if set to 0.")
	public static Integer limitExplosionSize = 12;
    @Config(name = "Don't stack drops", description = "Like pre-1.14")
    public static Boolean dontStackDrops = true;
    @Config(description = "If true, potion effects from the exploder will be applied to the damaged entities")
    public static Boolean applyEffectFromExploder = true;
	@Config(name = "Don't apply to non-entities", description = "If true, the overhaul will not be applied for explosions generated by non-entities. E.g. Supplementaries gunpowder")
	public static Boolean dontApplyToNonEntities = true;
	//@Config(description = "If enabled and Caverns and Chasms is present, Deepers explosions will pierce through blocks more (like Breaching creepers and Angry Creepers in Enhanced AI), knockback and damage are reduced by 40%.")
	//public static Boolean cavernsChasmsDeepers = false;

	public void init(Module module, boolean enabledByDefault, boolean canBeDisabled) {
		super.init(module, enabledByDefault, canBeDisabled);
		BASE_RESISTANCE_ADD_TAG = this.createDataKey("base_resistance_add");
		RAY_STRENGTH_MULTIPLIER_TAG = this.createDataKey("ray_strength_multiplier");
		KNOCKBACK_MULTIPLIER_TAG = this.createDataKey("knockback_multiplier");
		DAMAGE_MULTIPLIER_TAG = this.createDataKey("damage_multiplier");
	}

	/*@SubscribeEvent
	public void onDeeperSpawn(EntityJoinLevelEvent event) {
		if (!this.isEnabled()
				|| !cavernsChasmsDeepers
				|| !ModList.get().isLoaded("caverns_and_chasms")
				|| event.getEntity().getType() != CCEntityTypes.DEEPER.get())
			return;

		setBaseResistanceAdd(event.getEntity(), 0f);
		setKnockbackMultiplier(event.getEntity(), 0.60f);
		setDamageMultiplierTag(event.getEntity(), 0.75f);
	}*/

	/*@SubscribeEvent
	public void explosionPoofParticles(ExplosionEvent.Detonate event) {
		if (!this.isEnabled()
				|| !enablePoofParticles)
			return;

		Explosion e = event.getExplosion();
		if (((ExplosionAccessor) e).getLevel() instanceof ServerLevel level) {
			if (e instanceof ISOExplosion isoExplosion) {
				if (!isoExplosion.poofParticles)
					return;
				//ExplodeParticles.sync(level, isoExplosion);
			}
		}
	}*/

	//Setting the lowest priority so other mods can change explosions params before creating the ITExplosion
	@SubscribeEvent(priority = EventPriority.LOWEST)
	public void replaceExplosionWithITRExplosion(ExplosionEvent.Start event) {
		if (!this.isEnabled()
				|| !(event.getLevel() instanceof ServerLevel level)
				|| (event.getExplosion().getDirectSourceEntity() != null && event.getExplosion().getDirectSourceEntity().getType().is(ENTITY_BLACKLIST)))
			return;
		if (event.getExplosion().getDirectSourceEntity() == null && dontApplyToNonEntities)
			return;

		event.setCanceled(true);
		Explosion e = event.getExplosion();
		double y = e.center().y;
		if (((ExplosionAccessor) e).getSource() != null && explosionAtHalfEntity)
			y += ((ExplosionAccessor) e).getSource().getBbHeight() / 2d;
		ISOExplosion.explode(level, ((ExplosionAccessor) e).getSource(), ((ExplosionAccessor) e).getDamageSource(), ((ExplosionAccessor) e).getDamageCalculator(), e.center().x, y, e.center().z, e.radius(), ((ExplosionAccessor) e).getFire(), e.getBlockInteraction(), e.getSmallExplosionParticles(), e.getLargeExplosionParticles(), e.getExplosionSound(), true);
	}

	public static boolean shouldTakeReducedKnockback(Entity entity) {
		if (!(entity instanceof LivingEntity))
			return true;

		return entity.getType().is(KNOCKBACK_BLACKLIST);
	}

	/// Vanilla is 0.3
	public static void setBaseResistanceAdd(Entity entity, float baseResistanceAdd) {
		ModNBTData.put(entity, BASE_RESISTANCE_ADD_TAG, baseResistanceAdd);
	}

	public static float getBaseResistanceAdd(@Nullable Entity entity) {
		return entity != null && ModNBTData.contains(entity, BASE_RESISTANCE_ADD_TAG) ? ModNBTData.get(entity, BASE_RESISTANCE_ADD_TAG, Float.class) : 0.3f;
	}

	/// Vanilla is 0.3
	public static void setRayStrengthMultiplier(Entity entity, float rayStrengthMultiplier) {
		ModNBTData.put(entity, RAY_STRENGTH_MULTIPLIER_TAG, rayStrengthMultiplier);
	}

	public static float getRayStrengthMultiplier(@Nullable Entity entity) {
		return entity != null && ModNBTData.contains(entity, RAY_STRENGTH_MULTIPLIER_TAG) ? ModNBTData.get(entity, RAY_STRENGTH_MULTIPLIER_TAG, Float.class) : 0.3f;
	}

	public static void setKnockbackMultiplier(Entity entity, float knockbackMultiplier) {
		ModNBTData.put(entity, KNOCKBACK_MULTIPLIER_TAG, knockbackMultiplier);
	}

	public static float getKnockbackMultiplier(@Nullable Entity entity) {
		return entity != null && ModNBTData.contains(entity, KNOCKBACK_MULTIPLIER_TAG) ? ModNBTData.get(entity, KNOCKBACK_MULTIPLIER_TAG, Float.class) : 1f;
	}

	public static void setDamageMultiplierTag(Entity entity, float damageMultiplier) {
		ModNBTData.put(entity, DAMAGE_MULTIPLIER_TAG, damageMultiplier);
	}

	public static float getDamageMultiplier(@Nullable Entity entity) {
		return entity != null && ModNBTData.contains(entity, DAMAGE_MULTIPLIER_TAG) ? ModNBTData.get(entity, DAMAGE_MULTIPLIER_TAG, Float.class) : damageMultiplier.floatValue();
	}
}